config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :surftypes
  resources :cities
  resources :schools
  resources :coments
  resources :post_types
  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  #get 'about/index'
  #get 'promo/index'
  resources :posts do
    collection do
     get :newmagazine
     get :newsport
   end
	  resources :coments
    resources :likes
    resources :favorites
  end
  resources :subscribers



  root 'posts#postsMain'
  # root 'posts#index'

  get 'posts/index'
  get '/posts/hashtag/:name', to: 'posts#hashtags'
  # get '/posts/hashtag', to: 'posts#hashtags'
  get "postsMain" => "posts#postsMain", as: "postsMain"

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'landing', to: 'landingo#index'
  get 'styleguide', to: 'styleguide#index'
  get 'schools', to: 'schools#index'
  get 'cities', to: 'cities#index'
  get 'questions', to: 'questions#index'

  get "schoolsMain" => "schools#schoolsMain", as: "schoolsMain"
  get "schoolsCities" => "schools#schoolsCities", as: "schoolsCities"
  get "adminSchools" => "schools#adminSchools", as: "adminSchools"
  # get 'landing/index'
  # get 'styleguide/index'

  get "search", to: "search#search"
  # get "searchPage", to: "searchPage#searchPage"
  get "searchPage" => "search#searchPage", as: "searchPage"

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'
  get 'users/:id/following', :to => "users#following", :as => :following

  post "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_profile_session

  get 'admin', to: 'admin#index'
  get "changeRole" => "users#changeRole", as: "changeRole"

end

app/controllers/surftypes_controller.rb
class SurftypesController < ApplicationController
  before_action :set_surftype, only: [:show, :edit, :update, :destroy]

  # GET /surftypes
  # GET /surftypes.json
  def index
    @surftypes = Surftype.all
  end

  # GET /surftypes/1
  # GET /surftypes/1.json
  def show
  end

  # GET /surftypes/new
  def new
    @surftype = Surftype.new
  end

  # GET /surftypes/1/edit
  def edit
  end

  # POST /surftypes
  # POST /surftypes.json
  def create
    @surftype = Surftype.new(surftype_params)

    respond_to do |format|
      if @surftype.save
        format.html { redirect_to @surftype, notice: 'Surftype was successfully created.' }
        format.json { render :show, status: :created, location: @surftype }
      else
        format.html { render :new }
        format.json { render json: @surftype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surftypes/1
  # PATCH/PUT /surftypes/1.json
  def update
    respond_to do |format|
      if @surftype.update(surftype_params)
        format.html { redirect_to @surftype, notice: 'Surftype was successfully updated.' }
        format.json { render :show, status: :ok, location: @surftype }
      else
        format.html { render :edit }
        format.json { render json: @surftype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surftypes/1
  # DELETE /surftypes/1.json
  def destroy
    @surftype.destroy
    respond_to do |format|
      format.html { redirect_to surftypes_url, notice: 'Surftype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_surftype
      @surftype = Surftype.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def surftype_params
      params.require(:surftype).permit(:name, :description)
    end
end

app/helpers/surftypes_helper.rb
module SurftypesHelper
end

app/views/surftypes/_form.html.erb
<%= form_with(model: surftype, local: true) do |form| %>
  <% if surftype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(surftype.errors.count, "error") %> prohibited this surftype from being saved:</h2>

      <ul>
        <% surftype.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surftypes/edit.html.erb
<h1>Editing Surftype</h1>

<%= render 'form', surftype: @surftype %>

<%= link_to 'Show', @surftype %> |
<%= link_to 'Back', surftypes_path %>

app/views/surftypes/index.html.erb
<%= react_component 'M_Surftype', {surftype: @surftype, surftypes: @surftypes} %>

app/views/surftypes/new.html.erb
<h1>New Surftype</h1>

<%= render 'form', surftype: @surftype %>

<%= link_to 'Back', surftypes_path %>

app/views/surftypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @surftype.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @surftype.description %>
</p>

<%= link_to 'Edit', edit_surftype_path(@surftype) %> |
<%= link_to 'Back', surftypes_path %>