config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :surftypes
  resources :cities
  resources :schools
  resources :coments
  resources :post_types
  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  #get 'about/index'
  #get 'promo/index'
  resources :posts do
    collection do
     get :newmagazine
     get :newsport
   end
	  resources :coments
    resources :likes
    resources :favorites
  end
  resources :subscribers



  root 'posts#postsMain'
  # root 'posts#index'

  get 'posts/index'
  get '/posts/hashtag/:name', to: 'posts#hashtags'
  # get '/posts/hashtag', to: 'posts#hashtags'
  get "postsMain" => "posts#postsMain", as: "postsMain"

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'landing', to: 'landingo#index'
  get 'styleguide', to: 'styleguide#index'
  get 'schools', to: 'schools#index'
  get 'cities', to: 'cities#index'
  get 'questions', to: 'questions#index'

  get "schoolsMain" => "schools#schoolsMain", as: "schoolsMain"
  get "schoolsCities" => "schools#schoolsCities", as: "schoolsCities"
  get "adminSchools" => "schools#adminSchools", as: "adminSchools"
  # get 'landing/index'
  # get 'styleguide/index'

  get "search", to: "search#search"
  # get "searchPage", to: "searchPage#searchPage"
  get "searchPage" => "search#searchPage", as: "searchPage"

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'
  get 'users/:id/following', :to => "users#following", :as => :following

  post "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_profile_session

  get 'admin', to: 'admin#index'
  get "changeRole" => "users#changeRole", as: "changeRole"

end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :post_type
end

app/models/city.rb
class City < ApplicationRecord
  # belongs_to :school
  has_many :school

  mount_uploader :image, ImageUploader
end

app/models/coment.rb
class Coment < ApplicationRecord
  belongs_to  :post
  belongs_to  :user
  belongs_to  :parent, class_name: 'Coment', optional: true
  has_many    :replies, class_name: 'Coment', foreign_key: :parent_id, dependent: :destroy

  validates :body, presence: :true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followee, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
		# require 'elasticsearch/model'
class Post < ApplicationRecord

	# scope :filter_by_user, -> (user) { where user: user }
	scope :filter_by_category, -> (category) { where category: category }
	scope :filter_by_starts_with, -> (title) { where("title like ?", "%#{title}%")}

		# searchkick
		# include Elasticsearch::Model
		# include Elasticsearch::Model::Callbacks

		# validates :name, :presence => true
		validates :content, :presence => true,
											:length => { :minimum => 5 }

    has_many :coments, :dependent => :destroy
		has_many :likes, dependent: :destroy
		has_many :favorites, dependent: :destroy

		has_and_belongs_to_many :tags, :dependent => :destroy

		belongs_to :user
		belongs_to :category, optional: true
		belongs_to :post_type

		mount_uploader :image, ImageUploader

		# after_create do
		# 	post = Post.find_by(id: self.id)
		# 	hashtags = self.content.scan(/#\w+/)
		# 	hashtags.uniq.map do |hashtag|
		# 		tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
		# 		post.tags << tag
		# 	end
		# end
		#
		# before_update do
		# 	post = Post.find_by(id: self.id)
		# 	post.tags.clear
		# 	hashtags = self.content.scan(/#\w+/)
		# 	hashtags.uniq.map do |hashtag|
		# 		tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
		# 		post.tags << tag
		# 	end
		# end

		after_create do
			post = Post.find_by(id: self.id)
			hashtags = self.tagline.scan(/#\w+/)
			hashtags.uniq.map do |hashtag|
				tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
				post.tags << tag
			end
		end

		before_update do
			post = Post.find_by(id: self.id)
			post.tags.clear
			hashtags = self.tagline.scan(/#\w+/)
			hashtags.uniq.map do |hashtag|
				tag = Tag.find_or_create_by(name: hashtag.downcase.delete('#'))
				post.tags << tag
			end
		end

end

app/models/post_type.rb
class PostType < ApplicationRecord
  has_many :categories
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :city
  belongs_to :surftype

  scope :filter_by_city, -> (city) { where city: city }
  scope :filter_by_surftype, -> (surftype) { where surftype: surftype }
 #  scope :by_longitude, -> (min, max) { min && max ? where('longitude >= :min AND longitude <= :max', min: min, max: max) : all }
 # scope :by_latitude, -> (min, max) { min && max ? where('latitude >= :min AND latitude <= :max', min: min, max: max) : all }

  validates :name, :presence => true,
											:length => { :minimum => 5 }

  mount_uploader :image, ImageUploader
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/models/surftype.rb
class Surftype < ApplicationRecord
  has_many :school
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :likes, dependent: :destroy
  has_many :posts, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, :through => :favorites, :source => :post

  has_many :followed_users, foreign_key: :follower_id, class_name: 'Follow'
  has_many :followees, through: :followed_users
  has_many :following_users, foreign_key: :followee_id, class_name: 'Follow'
  has_many :followers, through: :following_users

  mount_uploader :image, AvatarUploader
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  # def render_with_hashtags(content)
  #   content.gsub(/#\w+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe
  # end

  def render_with_hashtags(tagline)
    tagline.gsub(/#\w+/){|word| link_to word, "/posts/hashtag/#{word.delete('#')}"}.html_safe
  end
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_sidemenu.html.erb
<div class="side_menu">
  <%= link_to "Публикации", admin_path %>
  <%= link_to "Люди", users_path %>
  <%= link_to "Категории", categories_path %>
</div>

app/views/admin/categories-admin.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>
<%= link_to 'New Category', new_category_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Display in navbar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.description %></td>
        <td><%= category.display_in_navbar %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/choosePost.html.erb
<%= link_to 'Новая статья', newarticle_posts_path %>
<%= link_to 'Создать медиаконтент', newmedia_posts_path %>
<%= link_to 'Добавить тренировку', newtraining_posts_path %>
<%= link_to 'Добавить тренировку', newtraining_posts_path %>

app/views/admin/index.html.erb
<% if user_signed_in? && current_user.isadmin == true%>
  <%= react_component 'M_AdminNavbar' %>
<% end %>

<%= react_component 'O_AdminPosts', { posts: @posts, post: @post, categories: @categories, category: @category } %>

<table>
  <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= image_tag(user.image.thumb.url, alt: 'Image') if user.image? %><span><%= user.username %></span></td>
          <td><%= user.id %></td>
          <% if user_signed_in? && current_user.isadmin == true %>
            <% if user.isadmin == true %>
              <td>Админ</td>
            <% end %>
          <% end %>
          <% if user_signed_in? && current_user.isadmin == true %>
            <% if user.isauthor == true %>
              <td>Автор</td>
            <% end %>
          <% end %>
          <td><span><%= link_to user.email, user %></span></td>
          <td><span><%= user.created_at.mday %>.<%= user.created_at.month %>.<%= user.created_at.year %><span/></td>
          <td><%= link_to 'Переназначить', edit_user_path(user) %></td>
          <td><%= link_to "Заблокировать", user, method: :delete, data: { confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
</table>