config/routes.rb
Rails.application.routes.draw do
  resources :questions
  resources :surftypes
  resources :cities
  resources :schools
  resources :coments
  resources :post_types
  resources :follows
  resources :categories
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  post 'users/:id/follow', to: "users#follow", as: "follow_user"
  post 'users/:id/unfollow', to: "users#unfollow", as: "unfollow_user"

  #get 'about/index'
  #get 'promo/index'
  resources :posts do
    collection do
     get :newmagazine
     get :newsport
   end
	  resources :coments
    resources :likes
    resources :favorites
  end
  resources :subscribers



  root 'posts#postsMain'
  # root 'posts#index'

  get 'posts/index'
  get '/posts/hashtag/:name', to: 'posts#hashtags'
  # get '/posts/hashtag', to: 'posts#hashtags'
  get "postsMain" => "posts#postsMain", as: "postsMain"

  get 'promo', to: 'promo#index'
  get 'about', to: 'about#index'
  get 'landing', to: 'landingo#index'
  get 'styleguide', to: 'styleguide#index'
  get 'schools', to: 'schools#index'
  get 'cities', to: 'cities#index'
  get 'questions', to: 'questions#index'

  get "schoolsMain" => "schools#schoolsMain", as: "schoolsMain"
  get "schoolsCities" => "schools#schoolsCities", as: "schoolsCities"
  get "adminSchools" => "schools#adminSchools", as: "adminSchools"
  # get 'landing/index'
  # get 'styleguide/index'

  get "search", to: "search#search"
  # get "searchPage", to: "searchPage#searchPage"
  get "searchPage" => "search#searchPage", as: "searchPage"

  get 'users', to: 'users#index'
  get 'users/:id' => 'users#show'
  delete 'users/:id', to: 'users#destroy'
  get 'users/:id/following', :to => "users#following", :as => :following

  post "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_profile_session

  get 'admin', to: 'admin#index'
  get "changeRole" => "users#changeRole", as: "changeRole"

end

app/models/school.rb
class School < ApplicationRecord
  belongs_to :city
  belongs_to :surftype

  scope :filter_by_city, -> (city) { where city: city }
  scope :filter_by_surftype, -> (surftype) { where surftype: surftype }
 #  scope :by_longitude, -> (min, max) { min && max ? where('longitude >= :min AND longitude <= :max', min: min, max: max) : all }
 # scope :by_latitude, -> (min, max) { min && max ? where('latitude >= :min AND latitude <= :max', min: min, max: max) : all }

  validates :name, :presence => true,
											:length => { :minimum => 5 }

  mount_uploader :image, ImageUploader
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @cities = City.all
    @surftypes = Surftype.all

    # if params.has_key?(:city)
    #   @city = City.find_by_name(params[:city])
    #   @schools = School.where(city: @city)
    #  #  schools = School.search(search_params.to_h.symbolize_keys)
    #  # render json: schools
    # else
    #   @schools = School.all
    # end

    # if params.has_key?(:surftype)
    #   @surftype = Surftype.find_by_name(params[:surftype])
    #   @schools = School.where(surftype: @surftype)
    # else
    #   @schools = School.all
    # end

    # @schools = School.where(nil)
    # @schools = @schools.filter_by_city(params[:city]) if params[:city].present?
    # @schools = @schools.filter_by_surftype(params[:surftype]) if params[:surftype].present?


    @schools = School.where(nil)
    filtering_params(params).each do |key, value|
      @schools = @schools.public_send("filter_by_#{key}", value) if value.present?
    end
  end


  def schoolsMain
    @cities = City.all
    @school = School.find_by_name(params[:school])
    @schools = School.all
    if params.has_key?(:city)
      @city = City.find_by_name(params[:city])
      @schools = School.where(city: @city)
    else
      @schools = School.all
    end

    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
    else
      @posts = Post.all
    end

  end

  def schoolsCities
    @cities = City.all
    @city = City.find_by_name(params[:city])
    @school = School.find_by_name(params[:school])
    @schools = School.all
  end

  def adminSchools
    @cities = City.all
    @city = City.find_by_name(params[:city])
    @school = School.find_by_name(params[:school])
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @surftypes = Surftype.all
    @surftype = Surftype.find(@school.surftype_id)

    if params.has_key?(:surftype)
      @surftype = Surftype.find_by_name(params[:surftype])
      @schools = School.where(surftype: @surftype)
    else
      @schools = School.all
    end

    if params.has_key?(:category)
      @category = Category.find_by_name(params[:category])
      @posts = Post.where(category: @category)
    else
      @posts = Post.all
    end

    if params.has_key?(:city)
      @city = City.find_by_name(params[:city])
      @schools = School.where(city: @city)
    else
      @schools = School.all
    end


  end

  # GET /schools/new
  def new
    @school = School.new
    @surftypes= [{id:"1", name:"классика"}, {id:"2", name:"сап"}, {id:"3", name:"вейк"}, {id:"4", name:"кайт"}, {id:"5", name:"винд"}, {id:"6", name:"скейт"}, {id:"7", name:"искусственная волна"}]
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'Школа успешно создана' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'Школа была обновлена' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'Школа была удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    def filtering_params(params)
      params.slice(:city, :surftype)
    end

    def search_params
      params.permit(:min_lng, :max_lng, :min_lat, :max_lat)
    end

    # Only allow a list of trusted parameters through.
    def school_params
      params.require(:school).permit(:name, :description, :longitude, :latitude, :city_id, :image, :inst, :tg, :fb, :website, :email, :tel, :service, :price, :season, :water, :wind, :wetsuit, :cafe, :shower, :room, :shop, :equip, :car, :surftype_id, :gallery)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_with(model: school, local: true) do |form| %>
  <% if school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
        <% school.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<%#= react_component 'O_SchoolForm', { school: @school, cities: @cities} %>
<div class="post-form">
  <h3 class = " A_H3 A_H3--black">Новая школа</h3>
  <div class="form-wrapper">

    <div>
      <%= link_to(image_tag(@school.image.thumb.url, alt: 'Image'), @school.image.url, target: '_blank') if @school.image? %>
      <div class="input--image">
        <%= form.file_field :image,
        class: 'btn btn--icons',
        style: "opacity: 0"
         %>
      </div>
    <div>


    <h5 class = "A_H5">Базовая информация</h5>

    <div class="form--item">
      <%= form.label "Название школы", class: 'input--label' %>
      <%= form.text_field :name,
      placeholder: 'Snowave Камчатка',
      class: 'input'  %>
    </div>
    <div class="form--item">
      <%= form.label "Краткое описание школы", class: 'input--label' %>
      <%= form.text_area :description,
      class: 'textarea'  %>
    </div>
    <div class="form--item">
      <%= form.label "Вид серфинга в школе", class: 'input--label' %>
      <%= form.select :surftype_id, Surftype.pluck(:name, :id) %>
    </div>

    <h5 class = "A_H5">Местоположение</h5>

    <div class="form--item">
      <%= form.label "Город", class: 'input--label' %>
      <%= form.select :city_id, City.pluck(:name, :id) %>
    </div>
  <div class="form--items-line">
    <div class="form--item">
      <%= form.label "Широта", class: 'input--label' %>
      <%= form.text_field :latitude,
      placeholder: 'Координаты',
      class: 'input' %>
    </div>
    <div class="form--item">
      <%= form.label "Долгота", class: 'input--label' %>
      <%= form.text_field :longitude,
      placeholder: 'Координаты',
      class: 'input' %>
    </div>
  </div>


    <h5 class = "A_H5">Услуги</h5>

    <div class="form--item">
      <%= form.label "Предлагаемые услуги", class: 'input--label' %>
      <%= form.cktext_area :service,
      placeholder: "Индивидуальная тренировка, групповая",
      class: 'textarea' %>
    </div>


    <div class="form--item">
      <%= form.label "Минимальная цена за услуги", class: 'input--label' %>
      <%= form.text_field :price,
      placeholder: "от 3600р",
      class: 'input' %>
    </div>


    <h5 class = "A_H5">Сведения о лучшем сезоне</h5>


  <div class="form--items-line">
    <div class="form--item">
      <%= form.label "Когда лучше кататься", class: 'input--label' %>
      <%= form.text_field :season,
      placeholder: "Месяц(а)",
      class: 'input' %>
    </div>
    <div class="form--item">
      <%= form.label "Температура воздуха", class: 'input--label' %>
      <%= form.text_field :wind,
      placeholder: "По Цельсию",
      class: 'input' %>
    </div>
  </div>
  <div class="form--items-line">
    <div class="form--item">
      <%= form.label "Температура воды", class: 'input--label' %>
      <%= form.text_field :water,
      placeholder: "По Цельсию",
      class: 'input' %>
    </div>
    <div class="form--item">
      <%= form.label "Толщина гидрика", class: 'input--label' %>
      <%= form.text_field :wetsuit,
      placeholder: "2.3 см",
      class: 'input' %>
    </div>
  </div>



    <h5 class = "A_H5">Удобства</h5>

    <div class="form--item" style="display: flex;">
      <%= form.check_box :room, class: 'custom-checkbox' %>
      <%= form.label "Раздевалки", class: 'input--label' %>
    </div>
    <div class="form--item" style="display: flex;">
      <%= form.check_box :shower, class: 'custom-checkbox' %>
      <%= form.label "Душевая", class: 'input--label' %>
    </div>
    <div class="form--item" style="display: flex;">
      <%= form.check_box :equip, class: 'custom-checkbox', type: "checkbox" %>
      <%= form.label "Оборудование", class: 'input--label' %>
    </div>
    <div class="form--item" style="display: flex;">
      <%= form.check_box :cafe, class: 'custom-checkbox' %>
      <%= form.label "Кафе по близости", class: 'input--label' %>
    </div>
    <div class="form--item" style="display: flex;">
      <%= form.check_box :shop, class: 'custom-checkbox' %>
      <%= form.label "Магазины рядом", class: 'input--label' %>
    </div>
    <div class="form--item" style="display: flex;">
      <%= form.check_box :car, class: 'custom-checkbox' %>
      <%= form.label "Легко доехать", class: 'input--label' %>
    </div>


    <h5 class = "A_H5">Фотогалерея</h5>

    <div class="form--item">
      <%= form.label "Загрузите фото", class: 'input--label' %>
      <%= form.cktext_area :gallery %>
    </div>

    <h5 class = "A_H5">Контакты</h5>

  <div class="form--items-line">
    <div class="form--item">
      <%= form.label "Почта", class: 'input--label' %>
      <%= form.email_field :email,
      placeholder: 'mmm@gmail.com',
      class: 'input' %>
    </div>
    <div class="form--item">
      <%= form.label "Телефон", class: 'input--label' %>
      <%= form.telephone_field :tel,
      placeholder: '+7(___) ___ __ __',
      class: 'input' %>
    </div>
  </div>

  <div class="form--items-line">
    <div class="form--item">
      <%= form.label "Сайт школы", class: 'input--label' %>
      <%= form.text_field :website,
      placeholder: 'surfschool.com',
      class: 'input' %>
    </div>

    <div class="form--item">
      <%= form.label "Инстаграм", class: 'input--label' %>
      <%= form.text_field :inst,
      placeholder: '@surf_school',
      class: 'input' %>
    </div>
  </div>

  <div class="form--items-line">
    <div class="form--item">
      <%= form.label "Телеграм", class: 'input--label' %>
      <%= form.text_field :tg,
      placeholder: '@surfero',
      class: 'input' %>
    </div>
    <div class="form--item">
      <%= form.label "Facebook", class: 'input--label' %>
      <%= form.text_field :fb,
      placeholder: '@surfero',
      class: 'input' %>
    </div>
  </div>

    <div class="form-submit">
      <%= form.submit 'Опубликовать', class: 'btn btn--main'%>
    </div>
  </div>
</div>
</div>


<% end %>

app/views/schools/adminSchools.html.erb
  <% if user_signed_in? && current_user.isadmin == true%>
    <%= react_component 'M_AdminNavbar' %>
    	<%= react_component 'O_AdminSchools', {surftypes: @surftypes, surftype: @surftype, school: @school, schools: @schools } %>
  <% end %>

app/views/schools/edit.html.erb
<%= render 'form', school: @school %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>
<% set_meta_tags title: 'Школы', description: 'Серфшколы России'%>
<% set_meta_tags og: {
    title: ['Школы']
}  %>


<div class="school-page">
	<div class="school-page_item">
		<%= react_component 'M_SchoolFound', {school: @school, schools: @schools, city: @city, cities: @cities} %>
		<div class="school-page_item-left">
			<div class="surftype__block">
				<h5 class="A_H5">Выбрать вид серфа</h5>
				<div class="surftype__block__select">
					<% Surftype.all.each do |st| %>
						<%= link_to st.name, request.params.merge(surftype: st.id), :class => "surftype--text" %>
					<% end %>
				</div>
			</div>
			<%= react_component 'M_SchoolPreview', {surftypes: @surftypes, surftype: @surftype, school: @school, schools: @schools } %>
      <%= react_component 'M_SchoolMore' %>
		</div>
      <%= react_component 'O_FooterSmall' %>
	</div>
	<div class="school-page_item school-page_item-map">
			<%= react_component 'M_MainMap', {school: @school, schools: @schools} %>
	</div>
</div>


<%= react_component 'M_CityOne' %>

<%#= link_to 'New City', new_city_path %>
<%#= link_to 'New School', new_school_path %>

app/views/schools/new.html.erb
<%= render 'form', school: @school %>

<%= link_to 'Back', schools_path %>

app/views/schools/schoolsCities.html.erb
<%= react_component 'O_CityCategories', {cities: @cities, city: @city, school: @school, schools: @schools } %>

app/views/schools/schoolsMain.html.erb
<%= react_component 'M_SchoolBanner'%>
<%= react_component 'M_SchoolMainTitleMobile'%>
<div class="O_PopularCities--block">
	<%= react_component 'O_PopularCities', {cities: @cities, city: @city, school: @school, schools: @schools } %>
</div>
<%= react_component 'M_SchoolPreviewSmall', {surftypes: @surftypes, surftype: @surftype, school: @school, schools: @schools } %>
<%= react_component 'M_BlockMore'%>
<%= react_component 'O_PostsEnding', { posts: @posts, post: @post, categories: @categories, category: @category } %>


<!-- <div class="" style="display:flex;">
	<% @schools.each do |school| %>
	 <div class="">
		 <div>
				<%#= link_to(image_tag(school.image.thumb.url, alt: 'Image'), school.image.url, target: '_blank') if school.image? %>
		 </div>
		 <div><%#= school.name %></div>
     <div><%#= school.city.name %></div>
		 <div>
			 <% if school.room == true %>
				 <p>Раздевалки</p>
			 <% end %>
		 <div>Тренировки от <%= school.price %></div>
		 <div><%#= link_to 'Show', school %></div>
		 <div><%#= link_to 'Edit', edit_school_path(school) %></div>
		 <div><%#= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></div>
	 </div>
	<% end %>
</div> -->

app/views/schools/show.html.erb
<p id="notice"><%= notice %></p>

<% set_meta_tags title: @school.name, description: @school.city.name %>

<%= react_component 'O_SchoolView', { school: @school} %>

<div class="final-admin-actions final-admin-actions-school">
  <% if user_signed_in? && current_user.isadmin == true %>
    <td><%= link_to 'Редактировать', edit_school_path(@school), class: 'btn btn--secondary' %></td>
    <td><%= link_to 'Удалить', @school, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn--secondary'  %></td>
  <% end %>
</div>

<%= react_component 'M_SchoolPreviewSmall', {surftypes: @surftypes, surftype: @surftype, school: @school, schools: @schools } %>
<%= react_component 'O_PostsEnding', { posts: @posts, post: @post, categories: @categories, category: @category } %>